### ISSUE TITLE
Usernames during registration

### ISSUE THREAD

**Issue by sielnet** [rmbinder/DeclarationOfMembership#10]
We have a problem with user names.

During registration a new user is not allowed to choose an user name.
We worked around this issue by creating a field "I want this user name".
Users could request a user name during registration.

In the new user approval phase an org member with special privileges copied the requested user name from the "I want this user name" field to the "user name" field and approved the registration.

We used this workaround because we were not able to add the real user name field to the registration form.
This worked nicely until recently. With the newer admidio updates or special org member group is not allowed to edit the user names anymore. Only admin is allowed to edit the user names now.
It makes sense. But I do not want to give admin privileges to the org members.

Should we be able to add the user name field to the registration form of DeclerationOfMembership?
I want to invest time to fix this issue at end of june.
In the meantime I would like to clarify the expected behaviour first.

**Comment by rmbinder** [comment]
The DeclarationOfMembership plugin was created to bring a new member's details into the system, but without a username (that's what the documentation says). The new member should NOT be able to log in. If a new member should also be able to register, the normal registration must always be used.

Nevertheless, I will take up the suggestion and try to include the username in the registration process.

**Comment by rmbinder** [comment]
The feature is implemented in the feature-user-login-name branch and roughly tested. Further tests should now be carried out. Above all, you should check whether everything fits if a user name already exists or if a new user name contains special characters.

**Comment by sielnet** [comment]
Thank you. I will try it out in the coming days.

Offtopic: We are a non profit org in germany. As far as I know we are not allowed to spend money on private persons.
Do you know how to donate money to admidio? Because as far as I understand it admidio is just a name and not a non profit itself. I am only asking you because you seem to have experience in this field. 
I would like to donate because admidio and specifically your plugins have improved our membership process significantly.
Is this a problem other orgs face? Should I open a thread in the admidio forum about it?

**Comment by rmbinder** [comment]
You can donate directly to Admidio at this URL: [https://admidio.org/donate.php](https://admidio.org/donate.php) (can be found in an Admidio installation under Einstellungen - Allgemein - Admidio Update). Here you can also donate to specific developers directly (my address https://ko-fi.com/rmbinder will be added in about 2 weeks)

**Comment by sielnet** [comment]
We have tested it in many ways and it is good enough for our using scenarios. All special characters that could cause as problems are cut off during the registration.

Thank you.
