### ISSUE TITLE
Option to directly redirect to new registration form after successful registration

### ISSUE THREAD

**Issue by rajanski** [rmbinder/DeclarationOfMembership#3]
As of now, there is this form after havin registered a new member:
![image](https://user-images.githubusercontent.com/5739684/126963712-db5f3d9f-0872-4ab5-83d1-e950b1838eec.png)
Is there a possibility to avoid this and directly re-open a new empty registration form (for a kiosk-like terminal)?

**Comment by rmbinder** [comment]
I do not want to do without this query. This enables a family easily enter the data of another family member. It would, however, be possible to install a switch via the "Preferences" that switches this query on or off.

**Comment by rajanski** [comment]
> It would, however, be possible to install a switch via the "Preferences" that switches this query on or off.

Yes à switch would be the best solution
