### ISSUE TITLE
Logikfehler bei Registrierung wenn DNS nicht funktioniert

### ISSUE THREAD

**Issue by sielnet** [rmbinder/DeclarationOfMembership#6]
Wenn Admidio keine DNS Anfrage versenden kann, schlägt eine Registrierung fehl.
Das ist logisch falsch. Die Registierung sollte akzeptiert werden.
Stattdessen wird diese komplett gelöscht.

Der Fehler fiel auf, weil die Firewall ein Routing Problem hatte und dies zu DNS Fehlern auf der Admidio VM führte.

Der Fehler hängt mit dem Versenden der Bestätigungs E-Mail zusammen. 
Wenn der Fehler auftritt, wird dem Registrierenden auch eine Fehlermeldung über den nicht erfolgten Versand der E-Mail angezeigt. Also ein unregistriertes neues Mitglied erhält eine Serverseitge Fehlermeldung. Auch dies ist fraglich.

Schritte zum Debuggen:
-E-Mail Versand aktiviert haben (SMTP, ob relevant ist nicht bekannt)
-DNS kaputt machen auf der Admidio VM
-Online-Beitrittserklärung ausfüllen
-Registrierung wird mit Fehlermeldung entgegengenommen, allerdings wird diese in Wahrrheit gelöscht

Ob der Fehler in Admidio oder in diesen Plugin liegt ist auch unbekannt.
Da ich aktuell mit dem Studium eingespannt bin, hatte ich leider keine Zeit dies weiter zu Untersuchen.

Falls es beabsichtigt ist, die Registrierung nur bei erfolgreich versendeter E-Mail zu akzeptieren, dann wäre das Problem dass es Niemand mitbekommt in dem geschilderten Fall. Ein neues Mitlgied hat sich an uns gewand und uns über den Fehler seiner Registrierung informiert. Nur war die Registrierung nicht vorzufinden.

**Comment by rmbinder** [comment]
Das sieht mir nach einem Fehler von Admidio aus. Das Plugin ist im Grunde nur ein anderes Frontend einer Registrierung. Nach dem Eingeben und Absenden der Daten wird es wie eine normale Registrierung weiter bearbeitet.
Ich werde das prüfen.

**Comment by sielnet** [comment]
Okay. Vielen Dank. Ich warte zuerst auf eine Rückmeldung und melde mich danach beim Admidio Projekt.

**Comment by rmbinder** [comment]
So wie ich es bereits vermutet hatte,  liegt der Fehler bzw. die Ursache nicht am Plugin, sondern an Admidio. Im Plugin wird dieselbe Prozedur zum Speichern angewendet, wie bei einer normalen Registrierung.

Innerhalb der Funktion save wird die E-Mail versendet. Dies funktioniert nicht, weil kein SMTP-Server gefunden wird und der SMTP-Server wird nicht gefunden, weil DNS nicht vorhanden oder fehlerhaft  ist, ergo, die Funktion zum Versenden der Mail ruft eine Exception aus und die Registrierung wird nicht abgeschlossen..

Am Bildschirm ist dann zu sehen: 

Die E-Mail konnte nicht an xxx gesendet werden.
Folgender Fehler ist aufgetreten:
SMTP-Fehler: Konnte keine Verbindung zum SMTP-Host herstellen. Failed to connect to server.

Der Code zum Senden der Registrierungsmail sollte eventuell aus der save-Funktion herausgelöst und separat abgehandelt werden.
