### ISSUE TITLE
Custom Auto-Reply Mail

### ISSUE THREAD

**Issue by benhartwich** [rmbinder/DeclarationOfMembership#7]
Hi,

is it anyhow possible to send a custom mail (template) whenever anyone has sent a declaration of membership form? E.g. we would like to send infos about bank transfer for annual subscription. 

Regards,

**Comment by rmbinder** [comment]
With each new registration, a system notification is already sent. A custom mail with more information should also be possible.

**Comment by benhartwich** [comment]
Ok, thanks - if we can pay for this feature let me know.

**Comment by rmbinder** [comment]
Hello Ben, 
what data should be sent in the custom mail. 
Can you send me a sample of what an email should look like?

**Comment by benhartwich** [comment]
Hi,

it can be a simple text mailing whenever a new user has submitted the declaration form. This mail should be sent from a specific mail address (nice to have) and this would be an example mail body:

_Wir freuen uns sehr über Ihre Mitgliedschaftsanmeldung zu unserem Arbeitskreis.
Die laufenden Informationen über die Veranstaltungen des Arbeitskreises und der Sternwarte Gahberg und über besondere Ereignisse am Sternenhimmel erhalten Sie künftig via email zugesandt, die Vereinszeitung kommt zusätzlich (in Österreich) als Druckausgabe mit der Post.

Mitgliedsbeitrag – wir bitten um Überweisung auf unser Vereinskonto: 
IBAN: XY , BIC: XY bei der VKB-Bank XY
Der Mitgliedsbeitrag  beträgt: 
für Erwerbstätige 19 Euro jährlich und für Jugendliche ohne Einkommen 11 Euro jährlich.
Wir freuen uns sehr, wenn Sie unseren Mitgliedsbeitrag mit einer Spende aufrunden.

Der Führungsbetrieb auf der Sternwarte findet wieder statt. Die Termine der Führungen werden nicht veröffentlicht, sondern an unsere Mitglieder und vorgemerkten Interessenten via mail bekanntgegeben – Sie erhalten diese Infos künftig. Die Termine werden jeweils ca. 2 bis 3 Tage vorher mitgeteilt. Als Mitglied zahlen Sie (und Ihre nahen Angehörige) keinen Eintritt._

**Comment by rmbinder** [comment]
The new Auto-reply mail function has been implemented in branch v2.2.0. Please check and test.

**Comment by benhartwich** [comment]
Thanks, looks great and works. Is it anyhow possible to customize the admin notification about new registrations?

**Comment by rmbinder** [comment]
Amidio - Preferences - General - System notifications - Notification after a new registration

**Comment by benhartwich** [comment]
Thanks
